AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Template for cloudwatch-alert-macro

  '
Resources:
  AlarmMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: AlarmMacro
      FunctionName:
        Fn::GetAtt:
        - AlarmMacroFunction
        - Arn
  AlarmMacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AlarmMacroFunction
      Description: Lambda Function for Alarm macro that appends alarms to specified
        resources in cloudformation templates
      Handler: alarm_macro.handler
      MemorySize: 128
      Runtime: python3.6
      Timeout: 60
      CodeUri: s3://cf-templates-io3rm3l4grtz-eu-west-1/76f112a8492da03340fe47017a8cb40b
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SNSTopic:
            Ref: MonitoringTopic
  MonitoringTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: Default-CloudWatch-Alarm-Topic
